### ISSUE TITLE
The addon has been removed from the Chrome store

### ISSUE THREAD

**Issue by jhsrennie** [dvdfreitag/SE-Chat-MathJax#2]
The SE Chat Mathjax addon has been removed from the Chrome store. Would it be possible to fix whatever caused it to be removed and resubmit it?

Thanks :-)

**Comment by dvdfreitag** [comment]
The removal is due to an update to the chrome extension manifest. More specifically, due to changes with the permissions system becoming far more granular.

There was a hard cutoff date for extensions using the old manifest which request certain permissions to update to the new manifest version, and I missed the deadline.

I haven't had much time to look into it, but now that I know there's someone out there that wants it back, I'll give it more priority :b

**Comment by jhsrennie** [comment]
Thanks :-) If is of use (probably not) I have been attempting to get it to work but cannot get it to allow access to Jax.js. Details at https://github.com/jhsrennie/SE-Chat-MathJax

**Comment by jhsrennie** [comment]
I know have the addon working again. I'll create a pull request but check it carefully as I got it working just by hacking until it worked so I don't have that much confidence in my changes.

**Comment by dvdfreitag** [comment]
I have updated the extension on the Chrome Store and submitted a request for review
